# Generated by Django 2.1.7 on 2019-02-14 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(('list_config', '0001_initial'))]

    initial = True

    dependencies = [
        ('desks', '0001_rebirth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Mis à jour à')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('ordering', models.CharField(blank=True, max_length=200, verbose_name='Tri')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listconfig_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_configs', to='desks.Desk', verbose_name='Desk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listconfig_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'List Config',
            },
        ),
        migrations.AlterUniqueTogether(
            name='listconfig',
            unique_together={('desk', 'name')},
        ),
    ]
