# Generated by Django 2.2.14 on 2020-08-07 08:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_config', '0001_rebirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='listconfig',
            name='columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Colonnes'),
        ),
    ]
