# Generated by Django 2.1.7 on 2019-02-14 10:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('activity_stream', '0001_initial'), ('activity_stream', '0002_auto_20151028_2014'), ('activity_stream', '0003_auto_20151215_1347'), ('activity_stream', '0004_auto_20160331_1307'), ('activity_stream', '0005_auto_20170623_1517'), ('activity_stream', '0006_rename_public_forms_actions'), ('activity_stream', '0007_auto_20171127_1047'), ('activity_stream', '0008_activity_diff'), ('activity_stream', '0009_move_html_diff_data'), ('activity_stream', '0010_migrate_diff_data'), ('activity_stream', '0011_clean_duplicate_target_action_object'), ('activity_stream', '0012_remove_reversion'), ('activity_stream', '0013_migrate_campaign_to_project'), ('activity_stream', '0014_migrate_actor_to_user'), ('activity_stream', '0015_migrate_actor_to_user'), ('activity_stream', '0016_rename_user_to_actor'), ('activity_stream', '0017_auto_20180426_1212'), ('activity_stream', '0018_activity_action_object_str'), ('activity_stream', '0019_init_comment_activity'), ('activity_stream', '0020_clean_activities_target'), ('activity_stream', '0021_auto_20181109_1015')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desks', '0001_rebirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254, verbose_name="Email de l'utilisateur")),
                ('actor_identifier', models.CharField(blank=True, max_length=63, null=True, verbose_name="Identifiant de l'utilisateur")),
                ('verb', models.CharField(choices=[('accepted_idea', 'Proposition acceptée'), ('asset_linked', 'Fichier lié'), ('asset_unlinked', 'Fichier retiré'), ('cancelled_rejection', 'a annulé le refus de la proposition'), ('closed', 'Clôture'), ('commented', 'Commentaire'), ('copied', 'Copie depuis'), ('created', 'Création'), ('deleted', 'Suppression'), ('hidden', 'Suppression'), ('joined_the_team', 'Nouvel utilisateur'), ('merged_review', 'Intégration des modifications de'), ('put_in_trash', 'Mis à la corbeille'), ('rejected_idea', 'Proposition rejetée'), ('reopened', 'Rouvert'), ('restored', 'Restauration'), ('restored_from_trash', 'Restauration de la corbeille'), ('validated', 'Validation du partage'), ('did_not_validated', 'Rejet du partage'), ('review_content_updated', 'Mise à jour du contenu partagé'), ('revoked', 'Révocation'), ('saved_new_version', 'Nouvelle version'), ('shared', 'Partage'), ('task_created', 'Création de tâche'), ('task_deleted', 'Suppression de tâche'), ('task_done', 'Tâche effectuée'), ('task_updated', 'Modification de tâche'), ('updated', 'Modification'), ('updated_workflow', 'Statut de workflow modifié'), ('upgrade_major_version', 'Version majeure créée'), ('accepted', 'a accepté'), ('approved', 'a approuvé'), ('published', 'a marqué [Publié]'), ('send_back_to_edition', 'a marqué [Brouillon]'), ('sent_for_approval', 'a partagé'), ('submitted_for_approval', 'a marqué [A Valider]'), ('send_to_publication', 'a marqué [A Publier]'), ('unpublished', 'a annulé la publication et marqué comme [Brouillon]'), ('unshared', 'a annulé le partage'), ('update_current_version', 'a mis à jour la version courante')], max_length=100, verbose_name='Verbe')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_str', models.CharField(blank=True, max_length=5000)),
                ('action_object_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_object_str', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diff', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('old_html_diff', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object', to='contenttypes.ContentType')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor', to=settings.AUTH_USER_MODEL)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stream', to='desks.Desk', verbose_name='Desk')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
