# Generated by Django 2.1.7 on 2019-02-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_rebirth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'base_manager_name': 'objects', 'ordering': ['hierarchy'], 'verbose_name': 'Canal', 'verbose_name_plural': 'Canaux'},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='publishers',
        ),
    ]
