# Generated by Django 2.1.7 on 2019-08-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20190221_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelToken',
        ),
    ]
