# Generated by Django 2.2.14 on 2020-09-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20190930_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittercredential',
            name='channel',
        ),
        migrations.DeleteModel(
            name='FacebookCredential',
        ),
        migrations.DeleteModel(
            name='TwitterCredential',
        ),
    ]
