# Generated by Django 2.2.14 on 2020-10-05 12:04
from django.db import migrations
from django.db.models import F

from pilot.utils import noop


def copy_hierarchy_for_children(apps, schema_editor):
    Channel = apps.get_model('channels', 'Channel')

    # Update the name for child channels
    Channel.objects.filter(level__gt=0).update(name=F('hierarchy'))


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_auto_20200907_1317'),
    ]

    operations = [
        migrations.RunPython(copy_hierarchy_for_children, noop),
    ]
