# Generated by Django 2.2.14 on 2020-10-05 11:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200907_1317'),
        ('channels', '0008_copy_hierarchy_for_children'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Canal', 'verbose_name_plural': 'Canaux'},
        ),
        migrations.AddField(
            model_name='channel',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='channels', to='assets.Asset', verbose_name='Médias'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.RemoveField(
            model_name='channel',
            name='hierarchy',
        ),
        migrations.AddField(
            model_name='channel',
            name='hierarchy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Arborescence des contenus'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='channels_by_owners', to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=models.CharField(choices=[('idea', 'Proposition'), ('rejected', 'Rejeté'), ('active', 'Actif'), ('closed', 'Fermé'), ('copy', 'En cours de copie')], db_index=True, default='idea', max_length=16, verbose_name='Statut'),
        ),
    ]
