# Generated by Django 2.1.7 on 2019-04-08 09:44

from django.db import migrations
from django.db.models import F

from pilot.utils import noop

def update_filters_tracking_fields(apps, schema_editor):
    SavedFilter = apps.get_model('itemsfilters', 'SavedFilter')
    PublicSharedFilter = apps.get_model('itemsfilters', 'PublicSharedFilter')

    SavedFilter.objects.all().update(created_by=F('user'), updated_by=F('user'))

    for shared_filter in PublicSharedFilter.objects.select_related('saved_filter'):
        shared_filter.created_by_id = shared_filter.saved_filter.user_id
        shared_filter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('itemsfilters', '0002_auto_20190408_1132'),
    ]

    operations = [
        migrations.RunPython(update_filters_tracking_fields, noop),
    ]
