# Generated by Django 2.1.7 on 2019-04-08 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemsfilters', '0004_migrate_desk_shared_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalSharedFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internalsharedfilter_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Internal Shared Filter',
                'verbose_name_plural': 'Internal Shared Filters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='publicsharedfilter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Public Shared Filter', 'verbose_name_plural': 'Public Shared Filters'},
        ),
        migrations.RemoveField(
            model_name='savedfilter',
            name='is_desk_shared',
        ),
        migrations.AlterField(
            model_name='publicsharedfilter',
            name='saved_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_shared_filters', to='itemsfilters.SavedFilter', verbose_name='Saved filter'),
        ),
        migrations.AlterField(
            model_name='publicsharedfilter',
            name='token',
            field=models.CharField(max_length=32, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='publicsharedfilter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='internalsharedfilter',
            name='saved_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_shared_filters', to='itemsfilters.SavedFilter', verbose_name='Saved filter'),
        ),
        migrations.AddField(
            model_name='internalsharedfilter',
            name='users',
            field=models.ManyToManyField(related_name='internal_shared_filters', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires'),
        ),
    ]
