# Generated by Django 2.1.7 on 2019-07-19 08:58

from django.db import migrations
from django.http import QueryDict

from pilot.utils import noop


def migrate_owners_in_calendar_filters(apps, schema_editor):
    SavedFilter = apps.get_model("itemsfilters", "SavedFilter")

    for saved_filter in SavedFilter.objects.filter(type='calendar').filter(query__contains='owners'):
        query_dict = QueryDict(query_string=saved_filter.query, mutable=True)
        owners = query_dict.getlist('owners')
        query_dict.setlist('item_owners', owners)
        query_dict.setlist('project_owners', owners)
        query_dict.pop('owners')
        saved_filter.query = query_dict.urlencode()
        saved_filter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('itemsfilters', '0005_auto_20190408_1552'),
    ]

    operations = [
        migrations.RunPython(migrate_owners_in_calendar_filters, reverse_code=noop),
    ]
