# Generated by Django 2.1.7 on 2020-02-18 15:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsfilters', '0006_migrate_owners_in_calendar_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalsharedfilter',
            name='new_message',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Message'),
        ),
    ]
