# Generated by Django 2.1.7 on 2020-02-18 15:33

from django.db import migrations

from pilot.utils import noop
from pilot.utils.prosemirror.prosemirror import convert_text_to_prosemirror_doc


def migrate_message_to_rte(apps, schema_editor):
    InternalSharedFilter = apps.get_model('itemsfilters', 'InternalSharedFilter')

    for isf in InternalSharedFilter.objects.iterator():
        isf.new_message = convert_text_to_prosemirror_doc(isf.message)
        isf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('itemsfilters', '0007_internalsharedfilter_new_message'),
    ]

    operations = [
        migrations.RunPython(migrate_message_to_rte, noop),
    ]
