# Generated by Django 2.1.7 on 2020-02-18 15:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsfilters', '0008_migrate_message_to_rte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalsharedfilter',
            name='message',
        ),
        migrations.RenameField(
            model_name='internalsharedfilter',
            old_name='new_message',
            new_name='message',
        ),
    ]
