# Generated by Django 2.2.14 on 2020-10-30 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itemsfilters', '0009_auto_20200218_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalsharedfilter',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='publicsharedfilter',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='type',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, verbose_name='Mis à jour à'),
        ),
    ]
