# Generated by Django 2.1.7 on 2019-02-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0001_rebirth'),
        ('pilot_users', '0001_rebirth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitationtoken',
            unique_together={('desk', 'token')},
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='desk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to='desks.Desk', verbose_name='Desk'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='invitationtoken',
            name='organization',
        ),
    ]
