# Generated by Django 2.1.7 on 2019-02-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_users', '0002_auto_20190221_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotuser',
            name='wiped',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a subit un wipeout (suppression de ses données)", verbose_name='Wiped'),
        ),
    ]
