# Generated by Django 2.1.7 on 2019-03-14 08:47

from django.db import migrations

from pilot.utils import noop

def add_reminder_notification_preference(apps, schema_editor):
    PilotUser = apps.get_model("pilot_users", "PilotUser")

    for user in PilotUser.objects.all().iterator():
        user.notification_preferences['reminder'] = {'email': True, 'app': True}
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_users', '0004_pilotuser_timezone'),
    ]

    operations = [
        migrations.RunPython(add_reminder_notification_preference, reverse_code=noop),
    ]
