# Generated by Django 2.1.7 on 2019-02-14 10:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pilot.assets.models
import pilot.utils.search
import uuid


class Migration(migrations.Migration):

    replaces = [('assets', '0001_initial'), ('assets', '0002_auto_20160322_1411'), ('assets', '0003_auto_20160331_1307'), ('assets', '0004_auto_20170623_1517'), ('assets', '0005_auto_20170627_1531'), ('assets', '0006_auto_20171127_1047'), ('assets', '0007_add_uuid_field'), ('assets', '0008_populate_uuid_values'), ('assets', '0009_remove_uuid_null'), ('assets', '0010_auto_20171219_1150'), ('assets', '0011_auto_20180123_1014'), ('assets', '0012_migrate_asset_transloadit_to_conversions'), ('assets', '0013_init_search_fields'), ('assets', '0014_init_search_indicies'), ('assets', '0015_asset_hidden'), ('assets', '0016_auto_20180424_1741'), ('assets', '0017_auto_20180627_1101'), ('assets', '0018_reset_versions')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desks', '0001_rebirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Mis à jour à')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('partial_search_document', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uuid')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Titre')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, upload_to='assets/tmp', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, help_text='Vous pouvez saisir un lien vers un fichier', max_length=2000, verbose_name='Lien externe')),
                ('filetype', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Type de fichier')),
                ('extension', models.CharField(blank=True, max_length=500, null=True, verbose_name='Extension')),
                ('mime', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mime')),
                ('conversions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=pilot.assets.models.get_default_conversions, null=True, verbose_name='Conversions')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('license', models.PositiveIntegerField(blank=True, choices=[(1, 'copyright'), (2, 'creative commons'), (3, 'libre')], null=True, verbose_name='Licence')),
                ('copyright_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée des droits')),
                ('allowed_supports', models.PositiveIntegerField(blank=True, choices=[(1, 'print'), (2, 'web')], null=True, verbose_name='Supports autorisés')),
                ('is_guideline', models.BooleanField(default=False, verbose_name='Document de référence')),
                ('in_media_library', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False, verbose_name='Invisible')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='desks.Desk', verbose_name='Desk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='assets_asse_search__cdde8b_gin'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=pilot.utils.search.TrigramIndex(fields=['partial_search_document'], name='assets_asse_partial_5646bc_gin'),
        ),
    ]
