# Generated by Django 2.1.7 on 2019-09-24 08:01

from django.db import migrations

from pilot.utils import noop
from pilot.utils.prosemirror.prosemirror import convert_text_to_prosemirror_doc


def migrate_description_to_rte(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')

    for asset in Asset.objects.iterator():
        asset.new_description = convert_text_to_prosemirror_doc(asset.description)
        asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_new_description'),
    ]

    operations = [
        migrations.RunPython(migrate_description_to_rte, noop),
    ]
