# Generated by Django 2.1.7 on 2020-01-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_auto_20200130_1057'),
        ('assets', '0005_auto_20190930_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_by_folder', to='labels.Label', verbose_name='Dossier'),
        ),
    ]
