# Generated by Django 2.2.14 on 2020-10-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20201019_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='filetype',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, verbose_name='Type de fichier'),
            preserve_default=False,
        ),
    ]
