# Generated by Django 2.2.14 on 2020-10-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20201019_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='mime',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Mime'),
            preserve_default=False,
        ),
    ]
