# Generated by Django 2.2.14 on 2020-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20201030_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='html_alt',
            field=models.CharField(blank=True, max_length=500, verbose_name='Texte alternatif ( html )'),
        ),
        migrations.AddField(
            model_name='asset',
            name='html_caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Légende ( html )'),
        ),
        migrations.AddField(
            model_name='asset',
            name='html_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Titre ( html )'),
        ),
    ]
