# Generated by Django 2.2.14 on 2020-11-19 14:15
from django.db import migrations
from django.db.models import F

from pilot.utils import noop


def init_html_fields(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    Asset.objects.update(
        html_title=F('title'),
        html_alt=F('title'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20201119_1514'),
    ]

    operations = [
        migrations.RunPython(init_html_fields, noop),
    ]
