# Generated by Django 2.1.7 on 2019-02-14 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pilot.utils.models


class Migration(migrations.Migration):

    replaces = [('tasks', '0001_initial'), ('tasks', '0002_migrate_item_state_dates_to_tasks'), ('tasks', '0003_auto_20171206_1649'), ('tasks', '0004_translate_en_task_names')]

    initial = True

    dependencies = [
        ('desks', '0001_rebirth'),
        ('items', '0001_rebirth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Mis à jour à')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('name', models.TextField(verbose_name='Nom')),
                ('deadline', pilot.utils.models.NaiveDateTimeField(blank=True, null=True, verbose_name='Echeance')),
                ('done', models.BooleanField(default=False, verbose_name='Effectué')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Effectué à')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Ordre')),
                ('show_in_publishing_calendar', models.BooleanField(default=False, verbose_name='Apparait dans le calendrier éditorial')),
                ('hidden', models.BooleanField(default=False, verbose_name='Invisible')),
                ('can_be_hidden', models.BooleanField(default=True, verbose_name='Peut être rendu invisible')),
                ('with_significant_time', models.BooleanField(default=False, verbose_name="Utilise l'heure sur l'échéance")),
                ('freeze_content', models.BooleanField(default=False, verbose_name='Gèle le contenu')),
                ('is_publication', models.BooleanField(default=False, verbose_name='Publication')),
                ('assignees', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsables')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='desks.Desk', verbose_name='Desk')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_done', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='items.Item', verbose_name='Item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Mis à jour à')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskgroup_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_groups', to='desks.Desk', verbose_name='Desk')),
                ('tasks', models.ManyToManyField(related_name='task_group', to='tasks.Task', verbose_name='Tâches')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskgroup_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
