# Generated by Django 2.1.7 on 2019-04-12 10:07

from django.db import migrations

from pilot.utils import noop


def migrate_task_group_relationship(apps, schema_editor):
    TaskGroup = apps.get_model("tasks", "TaskGroup")

    for task_group in TaskGroup.objects.all().iterator():
        for task in task_group.tasks.all():
            task.task_group = task_group
            task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190412_1207'),
    ]

    operations = [
        migrations.RunPython(migrate_task_group_relationship, reverse_code=noop),
    ]
