# Generated by Django 2.1.7 on 2019-04-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_migrate_task_group_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.TaskGroup', verbose_name='Groupe de tâche'),
        ),
    ]
