# Generated by Django 2.1.7 on 2019-07-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_copied_from'),
        ('tasks', '0005_taskgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project', verbose_name='Project'),
        ),
    ]
