# Generated by Django 2.2.14 on 2020-09-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='with_significant_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='can_be_hidden',
            field=models.BooleanField(default=True, verbose_name='Peut être supprimée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='freeze_content',
            field=models.BooleanField(default=False, verbose_name='Verrouille le contenu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='items.Item', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='show_in_publishing_calendar',
            field=models.BooleanField(default=False, verbose_name='Apparait dans le calendrier de publication'),
        ),
    ]
