# Generated by Django 2.2.14 on 2020-09-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200907_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='freeze_content',
        ),
    ]
