# Generated by Django 2.2.14 on 2020-10-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_freeze_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='channels.Channel', verbose_name='Channel'),
        ),
    ]
