# Generated by Django 2.1.7 on 2019-03-11 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_rebirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects_by_members', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='projects_by_owners', to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
    ]
