# Generated by Django 2.1.7 on 2019-04-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190311_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Copié depuis'),
        ),
    ]
