# Generated by Django 2.1.7 on 2019-09-24 07:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_copied_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Description'),
        ),
    ]
