# Generated by Django 2.1.7 on 2019-09-24 08:01

from django.db import migrations

from pilot.utils import noop
from pilot.utils.prosemirror.prosemirror import convert_text_to_prosemirror_doc


def migrate_description_to_rte(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.iterator():
        project.new_description = convert_text_to_prosemirror_doc(project.description)
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_new_description'),
    ]

    operations = [
        migrations.RunPython(migrate_description_to_rte, noop),
    ]
