# Generated by Django 2.1.7 on 2019-09-24 08:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_migrate_description_to_rte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='new_description',
            new_name='description',
        ),
    ]
