# Generated by Django 2.2.14 on 2020-10-05 11:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190924_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AddField(
            model_name='project',
            name='hierarchy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Arborescence des contenus'),
        ),
    ]
