# Generated by Django 2.2.14 on 2020-10-05 12:01

from django.db import migrations

from pilot.utils import noop


def init_hierarchy(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.iterator():
        item_ids = (
            project.items
            .filter(hidden=False, in_trash=False)
            .order_by('json_content__title')
            .values_list('id', flat=True)
        )
        project.hierarchy = [
            {
                'type': 'item',
                'id': item_id
            }
            for item_id in item_ids
        ]
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201005_1355'),
    ]

    operations = [
        migrations.RunPython(init_hierarchy, noop),
    ]
