# Generated by Django 2.1.7 on 2020-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0001_rebirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='creation_forms_fields_visibles_by_default',
            field=models.BooleanField(default=False, verbose_name='Masquer les champs additionnels des formulaires de créations'),
        ),
    ]
