# Generated by Django 2.1.7 on 2020-03-25 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desks', '0002_desk_creation_forms_fields_visibles_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='desk_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desk',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desk_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='creation_forms_fields_visibles_by_default',
            field=models.BooleanField(default=False, verbose_name='Afficher par défaut tous les champs des formulaires de créations'),
        ),
    ]
