# Generated by Django 2.2.14 on 2020-09-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0003_add_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='color',
        ),
    ]
