# Generated by Django 2.1.7 on 2019-03-18 15:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_rebirth'),
        ('desks', '0001_rebirth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_assetright'),
        ('notifications', '0001_rebirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notification_sent', models.BooleanField(default=False, verbose_name='Notification envoyée ?')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Rappel annulé ?')),
                ('target_type', models.CharField(choices=[('task_deadline', 'Task deadline'), ('asset_right_expiry', 'Asset right expiry')], max_length=50, verbose_name='Type de rappel')),
                ('delta_unit', models.CharField(choices=[('hours', 'Heures'), ('days', 'Jours'), ('weeks', 'Semaines')], max_length=10, verbose_name='Unité du délai')),
                ('delta_value', models.PositiveIntegerField(verbose_name='Valeur du délai')),
                ('ripe_date_time', models.DateTimeField(verbose_name='Date-heure de déclenchement de la notification de rappel')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='desks.Desk', verbose_name='Desk')),
                ('notification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder', to='notifications.Notification', verbose_name='Objet notification créé')),
                ('target_asset_right', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='assets.AssetRight', verbose_name='Target asset right')),
                ('target_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.Task', verbose_name='Target task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='notificationfeed',
            name='activity_verbs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('accepted_idea', 'Proposition acceptée'), ('asset_linked', 'Fichier lié'), ('asset_unlinked', 'Fichier retiré'), ('cancelled_rejection', 'a annulé le refus de la proposition'), ('closed', 'Clôture'), ('commented', 'Commentaire'), ('copied', 'Copie depuis'), ('created', 'Création'), ('deleted', 'Suppression'), ('hidden', 'Suppression'), ('joined_the_team', 'Nouvel utilisateur'), ('merged_review', 'Intégration des modifications de'), ('put_in_trash', 'Mis à la corbeille'), ('rejected_idea', 'Proposition rejetée'), ('reopened', 'Ré-ouverture'), ('restored', 'Restauration'), ('restored_from_trash', 'Restauration de la corbeille'), ('validated', 'Validation du partage'), ('did_not_validated', 'Rejet du partage'), ('review_content_updated', 'Mise à jour du contenu partagé'), ('revoked', 'Révocation'), ('saved_new_version', 'Nouvelle version'), ('shared', 'Partage'), ('task_created', 'Création de tâche'), ('task_deleted', 'Suppression de tâche'), ('task_done', 'Tâche effectuée'), ('task_updated', 'Modification de tâche'), ('updated', 'Modification'), ('updated_workflow', 'Statut de workflow modifié'), ('upgrade_major_version', 'Version majeure créée')], max_length=100), blank=True, default=list, size=None),
        ),
    ]
