# Generated by Django 2.1.7 on 2019-03-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='token',
            field=models.CharField(default='', max_length=32, verbose_name='Token'),
            preserve_default=False,
        ),
    ]
