# Generated by Django 2.1.7 on 2019-03-19 15:20

from django.db import migrations

from pilot.utils import noop
from pilot.utils.token_generator import generate_token


def init_notifications_token(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")

    for notification in Notification.objects.all().iterator():
        notification.token = generate_token()
        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_token'),
    ]

    operations = [
        migrations.RunPython(init_notifications_token, reverse_code=noop),
    ]

