# Generated by Django 2.1.7 on 2019-04-08 09:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemsfilters', '0001_move_filter_models'),
        ('notifications', '0005_update_saved_filter_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationfeed',
            old_name='item_saved_filter',
            new_name='saved_filter',
        ),
        migrations.AlterUniqueTogether(
            name='notificationfeed',
            unique_together={('user', 'saved_filter')},
        ),
    ]
