# Generated by Django 2.1.7 on 2019-09-30 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20190408_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationfeed',
            name='activity_verbs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('accepted_idea', 'Proposition acceptée'), ('asset_linked', 'Fichier lié'), ('asset_unlinked', 'Fichier retiré'), ('cancelled_rejection', 'a annulé le refus de la proposition'), ('closed', 'Clôture'), ('commented', 'Commentaire'), ('copied', 'Copie depuis'), ('created', 'Création'), ('deleted', 'Suppression'), ('hidden', 'Suppression'), ('joined_the_team', 'Nouvel utilisateur'), ('put_in_trash', 'Mis à la corbeille'), ('rejected_idea', 'Proposition rejetée'), ('reopened', 'Ré-ouverture'), ('restored', 'Restauration'), ('restored_from_trash', 'Restauration de la corbeille'), ('review_content_updated', 'Mise à jour du contenu partagé'), ('revoked', 'Révocation'), ('shared', 'Partage'), ('started_edit_session', "Session d'édition"), ('task_created', 'Création de tâche'), ('task_deleted', 'Suppression de tâche'), ('task_done', 'Tâche effectuée'), ('task_updated', 'Modification de tâche'), ('updated', 'Modification'), ('updated_workflow', 'Statut de workflow modifié'), ('upgrade_major_version', 'Version majeure créée')], max_length=100), blank=True, default=list, size=None),
        ),
    ]
