# Generated by Django 2.1.7 on 2020-02-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20190930_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='on_object_contenttype',
            new_name='linked_object_content_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='on_object',
            new_name='linked_object_id',
        ),
    ]
