# Generated by Django 2.1.7 on 2020-02-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20200225_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[(type, type), (type, type), (type, type), (type, type), (type, type), (type, type), (type, type), (type, type), (type, type), (type, type), (type, type), (type, type), (type, type), (type, type)], db_index=True, default='legacy', max_length=100, verbose_name='Type de notification'),
            preserve_default=False,
        ),
    ]
