# Generated by Django 2.2.14 on 2020-10-19 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20200907_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Contenu de la notification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationfeed',
            name='activity_verbs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('accepted_idea', 'Proposition acceptée'), ('asset_linked', 'Fichier lié'), ('asset_unlinked', 'Fichier retiré'), ('cancelled_rejection', 'a annulé le refus de la proposition'), ('closed', 'Clôture'), ('commented', 'Commentaire'), ('copied', 'Copie depuis'), ('created', 'Création'), ('deleted', 'Suppression'), ('feedback_approved', 'Contenu validé'), ('feedback_rejected', 'Contenu non validé'), ('frozen', 'Verrouillage édition'), ('hidden', 'Suppression'), ('joined_the_team', 'Nouvel utilisateur'), ('put_in_trash', 'Mis à la corbeille'), ('rejected_idea', 'Proposition rejetée'), ('reopened', 'Ré-ouverture'), ('restored', 'Restauration'), ('restored_from_trash', 'Restauration de la corbeille'), ('revoked', 'Révocation'), ('shared', 'Partage'), ('started_edit_session', "Session d'édition"), ('task_created', 'Création de tâche'), ('task_deleted', 'Suppression de tâche'), ('task_done', 'Tâche effectuée'), ('task_updated', 'Modification de tâche'), ('unfrozen', 'Déverrouillage édition'), ('updated', 'Modification'), ('updated_workflow', 'Statut de workflow modifié'), ('create_major_version', 'Version majeure créée')], max_length=100), blank=True, default=list, size=None),
        ),
    ]
