# Generated by Django 2.2.14 on 2020-10-06 11:37

from django.db import migrations

from pilot.utils import noop


def prune_content_types(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label='south').delete()
    ContentType.objects.filter(app_label='django_comments').delete()
    ContentType.objects.filter(app_label='invitations').delete()
    ContentType.objects.filter(app_label='taggit').delete()
    ContentType.objects.filter(app_label='reversion').delete()
    ContentType.objects.filter(app_label='external_ideas').delete()
    ContentType.objects.filter(app_label='preset_tags').delete()
    ContentType.objects.filter(app_label='custom_ui').delete()
    ContentType.objects.filter(app_label='social').delete()
    ContentType.objects.filter(app_label='public_api').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(prune_content_types, noop),
    ]
