# Generated by Django 2.2.11 on 2020-07-09 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desks', '0003_add_user'),
        ('channels', '0006_auto_20190930_1650'),
        ('projects', '0006_auto_20190924_1022'),
        ('itemsfilters', '0009_auto_20200218_1636'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0021_auto_20200625_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('type', models.CharField(choices=[('item', 'item'), ('project', 'project'), ('channel', 'channel'), ('list', 'list'), ('calendar', 'calendar')], max_length=32, null=True, verbose_name='Type')),
                ('token', models.CharField(db_index=True, max_length=255, verbose_name='Token')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('password', models.CharField(blank=True, help_text='Un mot de passe (optionnel) pour protéger le partage.', max_length=254, verbose_name='Mot de passe')),
                ('message', models.TextField(blank=True, verbose_name='Message au destinataire')),
                ('is_editable', models.BooleanField(default=False, verbose_name='Items editables')),
                ('deactivated', models.BooleanField(default=False, verbose_name='Accès désactivé')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='channels.Channel', verbose_name='Canal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='desks.Desk', verbose_name='Desk')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='items.Item', verbose_name='Contenu')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='projects.Project', verbose_name='Projet')),
                ('saved_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='itemsfilters.SavedFilter', verbose_name='Saved filter')),
            ],
            options={
                'verbose_name': 'Partage',
                'verbose_name_plural': 'Partages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('edited', 'Edité')], max_length=32, verbose_name='Statut')),
                ('feedback_message', models.TextField(blank=True, verbose_name='Commentaire de relecture')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de relecture')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='desks.Desk', verbose_name='Desk')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='items.Item', verbose_name='Contenu')),
                ('sharing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='sharings.Sharing')),
            ],
            options={
                'verbose_name': 'Feedback de contenu',
            },
        ),
    ]
