# Generated by Django 2.2.11 on 2020-06-25 12:44

from django.db import migrations


from pilot.utils import noop


def _migrate_sharings(apps, schema_editor):
    Sharing = apps.get_model("sharings", "Sharing")
    ItemFeedback = apps.get_model("sharings", "ItemFeedback")
    ItemSharing = apps.get_model("items", "ItemSharing")
    PublicSharedFilter = apps.get_model("itemsfilters", "PublicSharedFilter")

    for shared_filter in PublicSharedFilter.objects.select_related('saved_filter').iterator():
        Sharing.objects.create(
            desk_id=shared_filter.saved_filter.desk_id,
            type=shared_filter.saved_filter.type,
            token=shared_filter.token,
            email=shared_filter.email,
            password=shared_filter.password,
            saved_filter_id=shared_filter.saved_filter_id,
            created_at=shared_filter.created_at,
            created_by=shared_filter.created_by
        )

    for item_sharing in ItemSharing.objects.select_related('item').iterator():
        sharing = Sharing.objects.create(
            desk_id=item_sharing.item.desk_id,
            type='item',
            token=item_sharing.token,
            email=item_sharing.email,
            password=item_sharing.password,
            message=item_sharing.comment,
            is_editable=item_sharing.is_editable,
            item_id=item_sharing.item_id,
            created_at=item_sharing.created_at,
            created_by=item_sharing.created_by,
        )

        if item_sharing.status != 'pending':
            ItemFeedback.objects.create(
                desk_id=item_sharing.item.desk_id,
                sharing_id=sharing.id,
                item_id=item_sharing.item_id,
                status=item_sharing.status,
                feedback_message=item_sharing.review_comment,
                created_at=item_sharing.reviewed_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('sharings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_migrate_sharings, reverse_code=noop),
    ]
