# Generated by Django 2.1.7 on 2019-02-14 10:19

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    replaces = [('queue', '0001_initial'), ('queue', '0002_auto_20190129_1448')]

    initial = True

    dependencies = [
        ('desks', '0001_rebirth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('job_id', models.CharField(max_length=100, verbose_name='UUID utilisé par RQ')),
                ('job_type', models.CharField(choices=[('asset_export', 'Asset Export'), ('copy_project', 'Copy Project'), ('desk_export', 'Desk Export'), ('item_type_update', 'Item Type Update'), ('saved_filter_export', 'Saved Filter Export'), ('saved_filter_notify', 'Saved Filter Notify'), ('search_vector_update', 'Search Vector Update')], max_length=30, verbose_name='Type de job')),
                ('state', models.CharField(choices=[('queued', 'En cours'), ('started', 'Démarré'), ('finished', 'Terminé'), ('failed', 'Erreur'), ('redis_down', 'Impossible de lancer la tâche'), ('zombie', 'Zombie')], default='queued', max_length=30, verbose_name='Etat')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Términé à')),
                ('args', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('kwargs', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('timeout', models.CharField(blank=True, max_length=15, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Data')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtracker_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='desks.Desk', verbose_name='Desk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
