# Generated by Django 2.1.7 on 2019-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_rebirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtracker',
            name='try_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Nombre d'essai"),
        ),
        migrations.AlterField(
            model_name='jobtracker',
            name='job_type',
            field=models.CharField(choices=[('all_items_xls_export', 'All Items XLS Export'), ('all_projects_xls_export', 'All Projects XLS Export'), ('all_users_xls_export', 'All Users XLS Export'), ('asset_export', 'Asset Export'), ('copy_project', 'Copy Project'), ('desk_export', 'Desk Export'), ('item_type_update', 'Item Type Update'), ('saved_filter_export', 'Saved Filter Export'), ('saved_filter_notify', 'Saved Filter Notify'), ('search_vector_update', 'Search Vector Update')], max_length=30, verbose_name='Type de job'),
        ),
    ]
