# Generated by Django 2.2.14 on 2020-09-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_auto_20190318_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtracker',
            name='job_type',
            field=models.CharField(choices=[('all_items_xls_export', 'All Items XLS Export'), ('all_projects_xls_export', 'All Projects XLS Export'), ('all_users_xls_export', 'All Users XLS Export'), ('asset_export', 'Asset Export'), ('copy_project', 'Copy Project'), ('desk_export', 'Desk Export'), ('item_type_update', 'Item Type Update'), ('mention_update', 'Mention Update'), ('notify', 'Notify'), ('saved_filter_export', 'Saved Filter Export')], max_length=30, verbose_name='Type de job'),
        ),
    ]
