# Generated by Django 2.1.7 on 2019-10-09 10:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('name', models.CharField(blank=True, help_text='Usage interne uniquement, non affiché aux utilisateurs', max_length=200, verbose_name='Nom')),
                ('type', models.CharField(blank=True, choices=[('release', 'Release'), ('downtime', 'Downtime')], max_length=100, verbose_name='Type de message')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Content')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(null=True, verbose_name='Lu le')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='users',
            field=models.ManyToManyField(related_name='messages', through='messaging.UserMessage', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
