# Generated by Django 2.1.7 on 2019-02-14 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('workflow', '0001_initial'), ('workflow', '0002_auto_20170522_1343'), ('workflow', '0003_auto_20170623_1517'), ('workflow', '0004_auto_20170627_1531'), ('workflow', '0005_auto_20171127_1047')]

    initial = True

    dependencies = [
        ('desks', '0001_rebirth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Mis à jour à')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Ordre')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Couleur')),
                ('with_significant_date', models.BooleanField(default=False, verbose_name='Date associable')),
                ('with_significant_time', models.BooleanField(default=False, verbose_name='Heure associable')),
                ('is_configurable', models.BooleanField(default=False, verbose_name='Etats configurable')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowstate_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_states', to='desks.Desk', verbose_name='Desk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflowstate_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'workflow state',
                'verbose_name_plural': 'workflow states',
                'ordering': ['order'],
            },
        ),
    ]
