# Generated by Django 2.1.7 on 2019-02-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_rebirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstate',
            name='is_configurable',
        ),
        migrations.RemoveField(
            model_name='workflowstate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workflowstate',
            name='with_significant_date',
        ),
        migrations.RemoveField(
            model_name='workflowstate',
            name='with_significant_time',
        ),
    ]
