# Generated by Django 2.2.11 on 2020-06-04 14:39

from django.db import migrations

from pilot.utils import noop


def migrate_white_workflow_states(apps, schema_editor):
    WorkflowState = apps.get_model('workflow', 'WorkflowState')
    WorkflowState.objects.filter(color='#ffffff').update(color='#CFD8DC')


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190221_1506'),
    ]

    operations = [
        migrations.RunPython(migrate_white_workflow_states, noop),
    ]
