# Generated by Django 2.2.11 on 2020-06-04 14:39

from django.db import migrations

from pilot.utils import noop


def migrate_initial_workflow_states(apps, schema_editor):
    WorkflowState = apps.get_model('workflow', 'WorkflowState')
    WorkflowState.objects.filter(color='#c0392b').update(color='#C62828')
    WorkflowState.objects.filter(color='#e67e22').update(color='#EF6C00')
    WorkflowState.objects.filter(color='#2ecc71').update(color='#558B2F')
    WorkflowState.objects.filter(color='#95a5a6').update(color='#CFD8DC')


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_migrate_white_workflow_states'),
    ]

    operations = [
        migrations.RunPython(migrate_initial_workflow_states, noop),
    ]
