# Generated by Django 2.2.14 on 2020-09-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_migrate_initial_workflow_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstate',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Couleur'),
        ),
    ]
