# Generated by Django 2.1.7 on 2019-02-14 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('organizations', '0001_initial'), ('organizations', '0002_auto_20160331_1307'), ('organizations', '0003_auto_20170623_1517'), ('organizations', '0004_auto_20170627_1531'), ('organizations', '0005_auto_20171127_1047'), ('organizations', '0006_remove_organization_slug'), ('organizations', '0007_auto_20180531_1039'), ('organizations', '0008_remove_organization_users'), ('organizations', '0009_auto_20180613_1346'), ('organizations', '0010_init_billing_name'), ('organizations', '0011_auto_20180613_1519'), ('organizations', '0012_auto_20180613_1523')]

    initial = True

    dependencies = [
         # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Mis à jour à')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, help_text="Une organisation non active n'est plus utilisable, les utilisateurs ne peuvent plus s'y connecter", verbose_name='Actif')),
                ('max_desks', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre maximum de desks')),
                ('billing_name', models.CharField(max_length=200, verbose_name='Nom de facturation')),
                ('billing_address', models.CharField(blank=True, max_length=500, verbose_name='Adresse de facturation')),
                ('billing_postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal de facturation')),
                ('billing_city', models.CharField(blank=True, max_length=200, verbose_name='Ville de facturation')),
                ('billing_vat', models.CharField(blank=True, max_length=50, verbose_name='N° de TVA')),
                ('manual_billing', models.BooleanField(default=False, help_text='Indique si cette organisation est facturée manuellement (pas de stripe auto)', verbose_name='Facturation manuelle')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, verbose_name='Stripe customer id')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=50, verbose_name='Stripe subscription id')),
                ('cgv_acceptance_date', models.DateTimeField(blank=True, help_text="Date/heure de clic sur la checkbox d'acceptation des CGV", null=True, verbose_name='Acceptation CGV')),
                # ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                # ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
