# Generated by Django 2.1.7 on 2019-09-24 08:01

from django.db import migrations

from pilot.utils import noop
from pilot.utils.prosemirror.prosemirror import convert_text_to_prosemirror_doc


def migrate_description_to_rte(apps, schema_editor):
    Target = apps.get_model('targets', 'Target')

    for target in Target.objects.iterator():
        target.new_description = convert_text_to_prosemirror_doc(target.description)
        target.save()


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_new_description'),
    ]

    operations = [
        migrations.RunPython(migrate_description_to_rte, noop),
    ]
