# Generated by Django 2.1.7 on 2019-10-01 07:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_migrate_description_to_rte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='description',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='new_description',
            new_name='description',
        ),
    ]
