# Generated by Django 2.2.14 on 2020-11-23 13:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desks', '0005_auto_20201030_1111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, verbose_name='Mis à jour à')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Créé le')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Invisible')),
                ('name', models.CharField(max_length=500, verbose_name='Nom')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=rest_framework.utils.encoders.JSONEncoder, verbose_name='Contenu')),
                ('is_home_page', models.BooleanField(default=False, verbose_name='Home Page')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikipage_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='desks.Desk', verbose_name='Desk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wikipage_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Page de wiki',
                'verbose_name_plural': 'Pages de wiki',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WikiPageRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Créé le')),
                ('name', models.CharField(max_length=500, verbose_name='Nom')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=rest_framework.utils.encoders.JSONEncoder, verbose_name='Contenu')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikipagerevision_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('wiki_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='wiki.WikiPage', verbose_name='Page de  wiki')),
            ],
            options={
                'verbose_name': 'Wiki page revision',
                'verbose_name_plural': 'Wiki page revisions',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
            },
        ),
    ]
