# Generated by Django 2.2.14 on 2020-11-23 10:48
from django.db import migrations
from django.utils import timezone

from pilot.utils import noop
from pilot.wiki.initial_wiki import INITIAL_WIKI_HOME_PAGE


def init_wiki_home_pages(apps, schema_editor):
    Desk = apps.get_model('desks', 'Desk')
    WikiPage = apps.get_model('wiki', 'WikiPage')

    for desk in Desk.objects.all():
        WikiPage.objects.create(
            desk=desk,
            created_by_id=1,
            updated_at=timezone.now(),
            name="Wiki",
            content=INITIAL_WIKI_HOME_PAGE,
            is_home_page=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_wiki_home_pages, noop),
    ]
