# Generated by Django 2.1.7 on 2019-02-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_rebirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available_pictures',
        ),
        migrations.RemoveField(
            model_name='item',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by_external_email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by_external_token',
        ),
        migrations.RemoveField(
            model_name='item',
            name='explicit_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='external_publication_error',
        ),
        migrations.RemoveField(
            model_name='item',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='item',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='item',
            name='investigations_needed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='photo_investigations_needed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='photographer_needed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='item',
            name='support_needed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='where',
        ),
    ]
