# Generated by Django 2.1.7 on 2019-04-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190405_1009'),
    ]

    operations = [
        migrations.AlterModelTable(name='ItemSavedFilter', table='itemsfilters_savedfilter'),
        migrations.AlterModelTable(name='ItemSharedFilter', table='itemsfilters_publicsharedfilter'),
    ]
