# Generated by Django 2.1.7 on 2019-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20190221_1506'),
        ('items', '0005_remove_filter_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='channels',
            field=models.ManyToManyField(blank=True, to='channels.Channel', verbose_name='Canaux'),
        ),
    ]
