# Generated by Django 2.1.7 on 2019-06-06 09:50

from django.db import migrations

from pilot.utils import noop

def migrate_item_channels(apps, schema_editor):
    Item = apps.get_model("items", "Item")

    for item in Item.objects.exclude(channel=None).iterator():
        item.channels.add(item.channel)


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_channels'),
    ]

    operations = [
        migrations.RunPython(migrate_item_channels, reverse_code=noop),
    ]
