# Generated by Django 2.1.7 on 2019-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_migrate_item_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='channel',
        ),
        migrations.AlterField(
            model_name='item',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='items', to='channels.Channel', verbose_name='Canaux'),
        ),
    ]
