# Generated by Django 2.1.7 on 2019-06-11 08:30

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item_types', '0005_auto_20190611_1030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_auto_20190606_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsnapshot',
            name='annotations_migration_failure',
        ),
        migrations.RemoveField(
            model_name='itemsnapshot',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='itemsnapshot',
            name='metadata',
        ),
        migrations.AddField(
            model_name='item',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Edit history'),
        ),
        migrations.AddField(
            model_name='itemsnapshot',
            name='editors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Editeurs'),
        ),
        migrations.AddField(
            model_name='itemsnapshot',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='itemsnapshot',
            name='item_type_snapshot',
            field=models.ForeignKey(null=True,  on_delete=django.db.models.deletion.CASCADE, to='item_types.ItemTypeSnapshot', verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='itemsnapshot',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début'),
        ),
        migrations.AddField(
            model_name='itemsnapshot',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Mis à jour à'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsnapshot',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsnapshot_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='items.Item', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='itemsnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsnapshot_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='review',
            name='item_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='items.ItemSnapshot', verbose_name='Version du contenu'),
        ),
        migrations.DeleteModel(
            name='AnnotationMigrationFailure',
        ),
    ]
