# Generated by Django 2.1.7 on 2020-03-09 16:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20190726_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_editor',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Last Editor'),
        ),
    ]
