# Generated by Django 2.1.7 on 2020-03-10 08:24

from django.db import migrations

from pilot.utils import noop


def init_last_editor(apps, schema_editor):
    Item = apps.get_model("items", "Item")

    for item in Item.objects.exclude(updated_by=None).iterator():
        item.last_editor = item.updated_by_id
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_last_editor'),
    ]

    operations = [
        migrations.RunPython(init_last_editor, reverse_code=noop),
    ]
