# Generated by Django 2.2.11 on 2020-07-24 11:23

from django.db import migrations

from pilot.utils import noop

def migrate_item_history(apps, schema_editor):
    Item = apps.get_model("items", "Item")
    ItemHistory = apps.get_model("items", "ItemHistory")

    for item in Item.objects.all().only('id', 'history', 'field_versions').iterator():
        item.field_versions = {}
        history_instances = []

        for field_name, changes in item.history.items():
            item.field_versions[field_name] = len(changes)

            history_instances.append(
                ItemHistory(
                    item_id=item.id,
                    field_name=field_name,
                    changes=changes
                )
            )

        ItemHistory.objects.bulk_create(history_instances)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auto_20200724_1209'),
    ]

    operations = [
        migrations.RunPython(migrate_item_history, reverse_code=noop),
    ]
