# Generated by Django 2.2.11 on 2020-06-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_item_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsharing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings_old', to='items.Item', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='itemsharing',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('edited', 'Edité')], default='pending', max_length=32, verbose_name='Statut'),
        ),
    ]
