# Generated by Django 2.2.14 on 2020-09-11 13:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20200910_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='frozen_message',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Commentaire verrouillage'),
        ),
    ]
