# Generated by Django 2.2.14 on 2020-10-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20200911_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='workflow_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='workflow.WorkflowState', verbose_name='État de workflow'),
        ),
        migrations.DeleteModel(
            name='ItemSharing',
        ),
    ]
