# Generated by Django 2.2.14 on 2020-10-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20201019_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabe'), ('bg_BG', 'Bulgare'), ('cs_CZ', 'Tchèque'), ('da_DK', 'Danois'), ('de_DE', 'Allemand'), ('el_GR', 'Grec'), ('en_US', 'Anglais'), ('es_ES', 'Espagnol'), ('et_EE', 'Estonien'), ('fi_FI', 'Finnois'), ('fr_FR', 'Français'), ('hr_HR', 'Japonais'), ('hu_HU', 'Hongrois'), ('it_IT', 'Italien'), ('lt_LT', 'Lituanien'), ('ja_JA', 'Japonais'), ('nl_NL', 'Néerlandais'), ('no_NO', 'Norvégien'), ('pl_PL', 'Polonais'), ('pt_PT', 'Portugais'), ('ro_RO', 'Roumain'), ('ru_RU', 'Russe'), ('sk_SK', 'Slovaque'), ('sl_SI', 'Slovène'), ('sv_SE', 'Suédois'), ('tr_TR', 'Turc'), ('zh_CN', 'Chinois')], db_index=True, default='', max_length=5, verbose_name='Langue du contenu'),
            preserve_default=False,
        ),
    ]
