# Generated by Django 2.2.14 on 2020-10-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_auto_20201030_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='linked_items',
        ),
    ]
