# Generated by Django 2.2.14 on 2021-01-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_remove_item_linked_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemHistory',
        ),
    ]
