# Generated by Django 2.1.7 on 2019-04-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_types', '0001_rebirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskGroup'),
        ),
    ]
