# Generated by Django 2.1.7 on 2019-04-09 15:04

from django.db import migrations

from pilot.utils import noop


def init_item_types_task_group(apps, schema_editor):
    ItemType = apps.get_model("item_types", "ItemType")

    for item_type in ItemType.objects.all().iterator():
        item_type.task_group = item_type.desk.task_groups.get()
        item_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('item_types', '0002_itemtype_task_group'),
    ]

    operations = [
        migrations.RunPython(init_item_types_task_group, reverse_code=noop),
    ]
