# Generated by Django 2.1.7 on 2019-05-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_types', '0003_init_item_types_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtypesnapshot',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='item_types.ItemType', verbose_name='Type de contenu'),
        ),
    ]
