# Generated by Django 2.1.7 on 2019-06-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_types', '0004_auto_20190521_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtypesnapshot',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',), 'verbose_name': 'Snapshot type de contenu', 'verbose_name_plural': 'Snapshots types de contenu'},
        ),
    ]
