# Generated by Django 2.1.7 on 2019-11-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_types', '0005_auto_20190611_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Icon name', default='File'),
            preserve_default=False
        ),
    ]
