# Generated by Django 2.1.7 on 2020-02-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_migrate_comment_to_rte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='new_comment',
            new_name='comment_content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
    ]
