# Generated by Django 2.2.14 on 2020-09-07 11:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200210_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Commentaire'),
        ),
    ]
