# Generated by Django 2.1.7 on 2019-02-14 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('labels', '0001_initial'), ('labels', '0002_auto_20170627_1531'), ('labels', '0003_auto_20171127_1047'), ('labels', '0004_auto_20180426_1113'), ('labels', '0005_migrate_label_target'), ('labels', '0006_migrate_tags_to_labels'), ('labels', '0007_auto_20181130_0952'), ('labels', '0008_init_label_order'), ('labels', '0009_auto_20190114_0950')]

    initial = True

    dependencies = [
        ('desks', '0001_rebirth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Mis à jour à')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('color', models.CharField(max_length=7, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('target_type', models.CharField(choices=[('asset_tags', 'asset_tags'), ('channel_type', 'channel_type'), ('item_tags', 'item_tags'), ('project_category', 'project_category'), ('project_priority', 'project_priority'), ('project_tags', 'project_tags')], max_length=100, verbose_name='Type de cible')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Ordre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='desks.Desk', verbose_name='Desk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_updated', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'label',
                'ordering': ['order'],
            },
        ),
    ]
