# Generated by Django 2.1.7 on 2019-03-15 15:16

from django.db import migrations, models
from django.utils import timezone

from pilot.utils import noop


ASSET_RIGHT_MEDIUM = "asset_right_medium"
INITIAL_ASSET_RIGHT_MEDIUM = (
    dict(
        name="Affichage",
        color='#cccccc',
    ),
    dict(
        name="Film (web)",
        color='#cccccc',
    ),
    dict(
        name="Film (TV)",
        color='#cccccc',
    ),
    dict(
        name="Print (magazine)",
        color='#cccccc',
    ),
    dict(
        name="Print (Dépliant)",
        color='#cccccc',
    ),
    dict(
        name="Web",
        color='#cccccc',
    ),
)

def asset_right_medium(apps, schema_editor):
    Label = apps.get_model("labels", "Label")
    Desk = apps.get_model("desks", "Desk")

    now = timezone.now()

    for desk in Desk.objects.all():
        for i, dict_state in enumerate(INITIAL_ASSET_RIGHT_MEDIUM):
            Label.objects.create(
                desk=desk,
                created_by_id=1,
                updated_at=now,
                target_type=ASSET_RIGHT_MEDIUM,
                order=i,
                **dict_state
            )


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_rebirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='target_type',
            field=models.CharField(choices=[('asset_right_medium', 'asset_right_medium'), ('asset_tags', 'asset_tags'), ('channel_type', 'channel_type'), ('item_tags', 'item_tags'), ('project_category', 'project_category'), ('project_priority', 'project_priority'), ('project_tags', 'project_tags')], max_length=100, verbose_name='Type de cible'),
        ),

        migrations.RunPython(asset_right_medium, reverse_code=noop),


    ]
