# Generated by Django 2.1.7 on 2019-09-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_asset_right_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Couleur de fond'),
        ),
    ]
