# Generated by Django 2.1.7 on 2020-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_label_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='target_type',
            field=models.CharField(choices=[('asset_right_medium', 'asset_right_medium'), ('asset_folder', 'asset_folder'), ('asset_tags', 'asset_tags'), ('channel_type', 'channel_type'), ('item_tags', 'item_tags'), ('project_category', 'project_category'), ('project_priority', 'project_priority'), ('project_tags', 'project_tags')], max_length=100, verbose_name='Type de cible'),
        ),
    ]
