# Generated by Django 2.2.14 on 2020-10-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_migrate_initial_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Couleur de fond'),
            preserve_default=False,
        ),
    ]
