# Generated by Django 2.2.14 on 2020-10-30 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0007_auto_20201019_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='label',
            name='target_type',
            field=models.CharField(choices=[('asset_right_medium', 'asset_right_medium'), ('asset_folder', 'asset_folder'), ('asset_tags', 'asset_tags'), ('channel_type', 'channel_type'), ('item_tags', 'item_tags'), ('project_category', 'project_category'), ('project_priority', 'project_priority'), ('project_tags', 'project_tags')], db_index=True, max_length=100, verbose_name='Type de cible'),
        ),
        migrations.AlterField(
            model_name='label',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, verbose_name='Mis à jour à'),
        ),
    ]
